on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: on push / pull request
jobs:
  gitHubActionForPytest:
    name: GitHub Action for pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install iverilog
      run: sudo apt update && sudo apt install iverilog -y
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2
      with:
        java-version: '8'
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@master
      with:
        args: PYTHONPATH=. pytest tests/
